import * as React from 'react';

import { Title } from '../components/atoms';

const ImprintPage = () => {
	return (
		<div className="imprint">
			<div className="imprint__title">
				<Title>Imprint</Title>
			</div>
			<div className="imprint__provider">
				<strong>Provider</strong>
				<div>soosap GmbH</div>
				<div>Habsburgstrasse 44</div>
				<div>8400 Winterthur</div>
				<div>Switzerland</div>
				<div>Phone.: +41 76 699 35 59</div>
				<div>Email: feedback@jaffna.guide</div>
			</div>
			<div className="imprint__copyright">
				<strong>Copyright:</strong> soosap GmbH. All Rights Reserved. The text, images, graphics, sound files,
				animation files, video files and their arrangement on Jaffna Guide Internet sites are all subject to
				Copyright and other intellectual property protection. These objects may not be copied for commercial use
				or distribution, nor may these objects be modified or reposted to other web sites, apps or other digital
				content (hereinafter “Digital Offerings”). Some Jaffna Guide Offerings also contain material that is
				subject to the copyright rights of their providers.
			</div>
			<div className="imprint__google-analytics">
				<strong>Google Analytics:</strong> This website uses Google Analytics, a web analytics service provided
				by Google, Inc. ("Google"). Google Analytics uses "cookies", which are text files placed on your
				computer to help the website analyse how visitors use the site. The information generated by the cookie
				about your use of the website (including your IP address) will be transmitted to and stored by Google on
				servers in the United States. Google will use this information for the purpose of evaluating your use of
				the website, compiling reports on website activity for website operators and providing other services
				relating to website activity and internet usage. Google may also transfer this information to third
				parties where required to do so by law, or where such third parties process the information on Google's
				behalf. Google will not associate your IP address with any other data held by Google. You may refuse the
				use of cookies by selecting the appropriate settings on your browser, however please note that if you do
				this you may not be able to use the full functionality of this website. By using this website, you
				consent to the processing of data about you by Google in the manner and for the purposes set out above.
				You can prevent Google’s collection and use of data (cookies and IP address) by downloading and
				installing the browser plug-in available under https://tools.google.com/dlpage/gaoptout?hl=en.
				<br />
				<br />
				Further information concerning the terms and conditions of use and data privacy can be found at
				http://www.google.com/analytics/terms/gb.html or at
				http://www.google.com/intl/en_uk/analytics/privacyoverview.html
			</div>
		</div>
	);
};

export default ImprintPage;
